--
-- Script was generated by Devart dbForge Studio for MySQL, Version 9.2.105.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 03/09/2025 23:06:31
-- Server version: 10.4.27
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS academia_cursos;

CREATE DATABASE IF NOT EXISTS academia_cursos
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

--
-- Set default database
--
USE academia_cursos;

--
-- Create table `tipos_area`
--
CREATE TABLE IF NOT EXISTS tipos_area (
  id_tipo_area int(11) NOT NULL AUTO_INCREMENT,
  nombre varchar(50) NOT NULL,
  PRIMARY KEY (id_tipo_area)
)
ENGINE = INNODB,
AUTO_INCREMENT = 11,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

DELIMITER $$

--
-- Create procedure `sp_tipos_area_obtener_por_id`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_area_obtener_por_id (IN p_id int)
BEGIN
  SELECT
    id_tipo_area,
    nombre
  FROM tipos_area
  WHERE id_tipo_area = p_id;
END
$$

--
-- Create procedure `sp_tipos_area_listar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_area_listar ()
BEGIN
  SELECT
    id_tipo_area,
    nombre
  FROM tipos_area
  ORDER BY nombre;
END
$$

--
-- Create procedure `sp_tipos_area_eliminar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_area_eliminar (IN p_id int)
BEGIN
  DELETE
    FROM tipos_area
  WHERE id_tipo_area = p_id;
END
$$

--
-- Create procedure `sp_tipos_area_crear`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_area_crear (IN p_nombre varchar(50))
BEGIN
  INSERT INTO tipos_area (nombre)
    VALUES (p_nombre);
END
$$

--
-- Create procedure `sp_tipos_area_buscar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_area_buscar (IN p_term varchar(100))
BEGIN
  SELECT
    id_tipo_area,
    nombre
  FROM tipos_area
  WHERE nombre LIKE CONCAT('%', p_term, '%')
  ORDER BY nombre;
END
$$

--
-- Create procedure `sp_tipos_area_actualizar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_area_actualizar (IN p_id int, IN p_nombre varchar(50))
BEGIN
  UPDATE tipos_area
  SET nombre = p_nombre
  WHERE id_tipo_area = p_id;
END
$$

DELIMITER ;

--
-- Create table `areas`
--
CREATE TABLE IF NOT EXISTS areas (
  id_area int(11) NOT NULL AUTO_INCREMENT,
  id_tipo_area int(11) NOT NULL,
  nombre varchar(100) NOT NULL,
  PRIMARY KEY (id_area)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `fk_areas_tipos_area_idx` on table `areas`
--
ALTER TABLE areas
ADD INDEX fk_areas_tipos_area_idx (id_tipo_area);

--
-- Create foreign key
--
ALTER TABLE areas
ADD CONSTRAINT fk_areas_tipos_area FOREIGN KEY (id_tipo_area)
REFERENCES tipos_area (id_tipo_area) ON UPDATE CASCADE;

DELIMITER $$

--
-- Create procedure `sp_tipos_area_verificar_dependencias`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_area_verificar_dependencias (IN p_id_tipo_area int)
BEGIN
  SELECT
    COUNT(id_area) AS count
  FROM areas
  WHERE id_tipo_area = p_id_tipo_area;
END
$$

--
-- Create procedure `sp_areas_obtener_por_id`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_areas_obtener_por_id (IN p_id int)
BEGIN
  SELECT
    id_area,
    id_tipo_area,
    nombre
  FROM areas
  WHERE id_area = p_id;
END
$$

--
-- Create procedure `sp_areas_listar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_areas_listar ()
BEGIN
  SELECT
    a.id_area,
    a.nombre,
    ta.nombre AS tipo_area
  FROM areas a
    JOIN tipos_area ta
      ON a.id_tipo_area = ta.id_tipo_area
  ORDER BY a.nombre;
END
$$

--
-- Create procedure `sp_areas_eliminar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_areas_eliminar (IN p_id int)
BEGIN
  DELETE
    FROM areas
  WHERE id_area = p_id;
END
$$

--
-- Create procedure `sp_areas_crear`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_areas_crear (IN p_id_tipo_area int, IN p_nombre varchar(100))
BEGIN
  INSERT INTO areas (id_tipo_area, nombre)
    VALUES (p_id_tipo_area, p_nombre);
END
$$

--
-- Create procedure `sp_areas_buscar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_areas_buscar (IN p_term varchar(100))
BEGIN
  SELECT
    a.id_area,
    a.nombre,
    ta.nombre AS tipo_area
  FROM areas a
    JOIN tipos_area ta
      ON a.id_tipo_area = ta.id_tipo_area
  WHERE a.nombre LIKE CONCAT('%', p_term, '%')
  OR ta.nombre LIKE CONCAT('%', p_term, '%')
  ORDER BY a.nombre;
END
$$

--
-- Create procedure `sp_areas_actualizar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_areas_actualizar (IN p_id_area int, IN p_id_tipo_area int, IN p_nombre varchar(100))
BEGIN
  UPDATE areas
  SET id_tipo_area = p_id_tipo_area,
      nombre = p_nombre
  WHERE id_area = p_id_area;
END
$$

DELIMITER ;

--
-- Create table `sub_areas`
--
CREATE TABLE IF NOT EXISTS sub_areas (
  id_sub_area int(11) NOT NULL AUTO_INCREMENT,
  id_area int(11) NOT NULL,
  descripcion varchar(100) NOT NULL,
  numero_sub_area varchar(20) DEFAULT NULL,
  capacidad_maxima int(11) NOT NULL,
  PRIMARY KEY (id_sub_area)
)
ENGINE = INNODB,
AUTO_INCREMENT = 12,
AVG_ROW_LENGTH = 1489,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `fk_sub_areas_areas_idx` on table `sub_areas`
--
ALTER TABLE sub_areas
ADD INDEX fk_sub_areas_areas_idx (id_area);

--
-- Create foreign key
--
ALTER TABLE sub_areas
ADD CONSTRAINT fk_sub_areas_areas FOREIGN KEY (id_area)
REFERENCES areas (id_area) ON DELETE CASCADE ON UPDATE CASCADE;

DELIMITER $$

--
-- Create procedure `sp_sub_areas_obtener_por_id`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_sub_areas_obtener_por_id (IN p_id int)
BEGIN
  SELECT
    id_sub_area,
    id_area,
    descripcion,
    numero_sub_area,
    capacidad_maxima
  FROM sub_areas
  WHERE id_sub_area = p_id;
END
$$

--
-- Create procedure `sp_sub_areas_listar_simple`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_sub_areas_listar_simple ()
BEGIN
  SELECT
    sa.id_sub_area,
    CONCAT(a.nombre, ' - ', sa.descripcion) AS nombre_completo
  FROM sub_areas sa
    JOIN areas a
      ON sa.id_area = a.id_area
  ORDER BY a.nombre, sa.descripcion;
END
$$

--
-- Create procedure `sp_sub_areas_listar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_sub_areas_listar ()
BEGIN
  SELECT
    sa.id_sub_area,
    sa.descripcion,
    sa.numero_sub_area,
    sa.capacidad_maxima,
    a.nombre AS area_nombre
  FROM sub_areas sa
    JOIN areas a
      ON sa.id_area = a.id_area
  ORDER BY a.nombre, sa.descripcion;
END
$$

--
-- Create procedure `sp_sub_areas_eliminar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_sub_areas_eliminar (IN p_id int)
BEGIN
  DELETE
    FROM sub_areas
  WHERE id_sub_area = p_id;
END
$$

--
-- Create procedure `sp_sub_areas_crear`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_sub_areas_crear (IN p_id_area int,
IN p_descripcion varchar(100),
IN p_numero_sub_area varchar(20),
IN p_capacidad_maxima int)
BEGIN
  INSERT INTO sub_areas (id_area, descripcion, numero_sub_area, capacidad_maxima)
    VALUES (p_id_area, p_descripcion, p_numero_sub_area, p_capacidad_maxima);
END
$$

--
-- Create procedure `sp_sub_areas_buscar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_sub_areas_buscar (IN p_term varchar(100))
BEGIN
  SELECT
    sa.id_sub_area,
    sa.descripcion,
    sa.numero_sub_area,
    sa.capacidad_maxima,
    a.nombre AS area_nombre
  FROM sub_areas sa
    JOIN areas a
      ON sa.id_area = a.id_area
  WHERE sa.descripcion LIKE CONCAT('%', p_term, '%')
  OR sa.numero_sub_area LIKE CONCAT('%', p_term, '%')
  OR a.nombre LIKE CONCAT('%', p_term, '%')
  ORDER BY a.nombre, sa.descripcion;
END
$$

--
-- Create procedure `sp_sub_areas_actualizar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_sub_areas_actualizar (IN p_id_sub_area int,
IN p_id_area int,
IN p_descripcion varchar(100),
IN p_numero_sub_area varchar(20),
IN p_capacidad_maxima int)
BEGIN
  UPDATE sub_areas
  SET id_area = p_id_area,
      descripcion = p_descripcion,
      numero_sub_area = p_numero_sub_area,
      capacidad_maxima = p_capacidad_maxima
  WHERE id_sub_area = p_id_sub_area;
END
$$

--
-- Create procedure `sp_areas_verificar_dependencias`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_areas_verificar_dependencias (IN p_id_area int)
BEGIN
  SELECT
    COUNT(id_sub_area) AS count
  FROM sub_areas
  WHERE id_area = p_id_area;
END
$$

DELIMITER ;

--
-- Create table `roles`
--
CREATE TABLE IF NOT EXISTS roles (
  id_rol int(11) NOT NULL AUTO_INCREMENT,
  nombre_rol varchar(50) NOT NULL,
  descripcion varchar(255) DEFAULT NULL,
  PRIMARY KEY (id_rol)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `nombre_rol_UNIQUE` on table `roles`
--
ALTER TABLE roles
ADD UNIQUE INDEX nombre_rol_UNIQUE (nombre_rol);

--
-- Create table `usuarios`
--
CREATE TABLE IF NOT EXISTS usuarios (
  id_usuario int(11) NOT NULL AUTO_INCREMENT,
  id_rol int(11) NOT NULL,
  nombre_usuario varchar(50) NOT NULL,
  password_hash varchar(255) NOT NULL,
  email varchar(100) NOT NULL,
  nombre_completo varchar(150) NOT NULL,
  activo tinyint(1) NOT NULL DEFAULT 1,
  fecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  auth_2fa_code varchar(10) DEFAULT NULL,
  auth_2fa_expiry datetime DEFAULT NULL,
  PRIMARY KEY (id_usuario)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `nombre_usuario_UNIQUE` on table `usuarios`
--
ALTER TABLE usuarios
ADD UNIQUE INDEX nombre_usuario_UNIQUE (nombre_usuario);

--
-- Create index `email_UNIQUE` on table `usuarios`
--
ALTER TABLE usuarios
ADD UNIQUE INDEX email_UNIQUE (email);

--
-- Create index `fk_usuarios_roles_idx` on table `usuarios`
--
ALTER TABLE usuarios
ADD INDEX fk_usuarios_roles_idx (id_rol);

--
-- Create foreign key
--
ALTER TABLE usuarios
ADD CONSTRAINT fk_usuarios_roles FOREIGN KEY (id_rol)
REFERENCES roles (id_rol) ON UPDATE CASCADE;

DELIMITER $$

--
-- Create procedure `sp_usuarios_verificar_codigo_2fa`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_usuarios_verificar_codigo_2fa (IN p_id_usuario int,
IN p_codigo varchar(10))
BEGIN
  SELECT
    id_usuario
  FROM usuarios
  WHERE id_usuario = p_id_usuario
  AND auth_2fa_code = p_codigo
  AND auth_2fa_expiry > NOW();
END
$$

--
-- Create procedure `sp_usuarios_obtener_por_nombre`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_usuarios_obtener_por_nombre (IN p_nombre_usuario varchar(50))
BEGIN
  SELECT
    id_usuario,
    id_rol,
    nombre_usuario,
    password_hash,
    email,
    nombre_completo,
    activo
  FROM usuarios
  WHERE nombre_usuario = p_nombre_usuario
  AND activo = 1;
END
$$

--
-- Create procedure `sp_usuarios_obtener_por_id`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_usuarios_obtener_por_id (IN p_id_usuario int)
BEGIN
  SELECT
    u.id_usuario,
    u.id_rol,
    r.nombre_rol,
    u.nombre_usuario,
    u.email,
    u.nombre_completo,
    u.activo,
    u.fecha_creacion
  FROM usuarios u
    JOIN roles r
      ON u.id_rol = r.id_rol
  WHERE u.id_usuario = p_id_usuario;
END
$$

--
-- Create procedure `sp_usuarios_listar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_usuarios_listar ()
BEGIN
  SELECT
    u.id_usuario,
    u.id_rol,
    r.nombre_rol,
    u.nombre_usuario,
    u.email,
    u.nombre_completo,
    u.activo
  FROM usuarios u
    JOIN roles r
      ON u.id_rol = r.id_rol
  ORDER BY u.nombre_completo;
END
$$

--
-- Create procedure `sp_usuarios_guardar_codigo_2fa`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_usuarios_guardar_codigo_2fa (IN p_id_usuario int,
IN p_codigo varchar(10),
IN p_expiracion datetime)
BEGIN
  UPDATE usuarios
  SET auth_2fa_code = p_codigo,
      auth_2fa_expiry = p_expiracion
  WHERE id_usuario = p_id_usuario;
END
$$

--
-- Create procedure `sp_usuarios_eliminar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_usuarios_eliminar (IN p_id_usuario int)
BEGIN
  UPDATE usuarios
  SET activo = 0
  WHERE id_usuario = p_id_usuario;
END
$$

--
-- Create procedure `sp_usuarios_crear`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_usuarios_crear (IN p_id_rol int,
IN p_nombre_usuario varchar(50),
IN p_password_hash varchar(255),
IN p_email varchar(100),
IN p_nombre_completo varchar(150))
BEGIN
  INSERT INTO usuarios (id_rol, nombre_usuario, password_hash, email, nombre_completo, activo)
    VALUES (p_id_rol, p_nombre_usuario, p_password_hash, p_email, p_nombre_completo, 1);
END
$$

--
-- Create procedure `sp_usuarios_cambiar_password`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_usuarios_cambiar_password (IN p_id_usuario int,
IN p_password_hash varchar(255))
BEGIN
  UPDATE usuarios
  SET password_hash = p_password_hash
  WHERE id_usuario = p_id_usuario;
END
$$

--
-- Create procedure `sp_usuarios_actualizar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_usuarios_actualizar (IN p_id_usuario int,
IN p_id_rol int,
IN p_nombre_usuario varchar(50),
IN p_email varchar(100),
IN p_nombre_completo varchar(150),
IN p_activo tinyint(1))
BEGIN
  UPDATE usuarios
  SET id_rol = p_id_rol,
      nombre_usuario = p_nombre_usuario,
      email = p_email,
      nombre_completo = p_nombre_completo,
      activo = p_activo
  WHERE id_usuario = p_id_usuario;
END
$$

DELIMITER ;

--
-- Create table `tipos_documento`
--
CREATE TABLE IF NOT EXISTS tipos_documento (
  id_tipo_documento int(11) NOT NULL AUTO_INCREMENT,
  descripcion varchar(50) NOT NULL,
  longitud int(11) DEFAULT NULL,
  codigo_sunat varchar(2) DEFAULT NULL,
  PRIMARY KEY (id_tipo_documento)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

DELIMITER $$

--
-- Create procedure `sp_tipos_documento_obtener_por_id`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_documento_obtener_por_id (IN p_id int)
BEGIN
  SELECT
    id_tipo_documento,
    descripcion,
    longitud,
    codigo_sunat
  FROM tipos_documento
  WHERE id_tipo_documento = p_id;
END
$$

--
-- Create procedure `sp_tipos_documento_listar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_documento_listar ()
BEGIN
  SELECT
    id_tipo_documento,
    descripcion,
    longitud,
    codigo_sunat
  FROM tipos_documento
  ORDER BY descripcion;
END
$$

--
-- Create procedure `sp_tipos_documento_eliminar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_documento_eliminar (IN p_id int)
BEGIN
  DELETE
    FROM tipos_documento
  WHERE id_tipo_documento = p_id;
END
$$

--
-- Create procedure `sp_tipos_documento_crear`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_documento_crear (IN p_descripcion varchar(50),
IN p_longitud int,
IN p_codigo_sunat varchar(2))
BEGIN
  INSERT INTO tipos_documento (descripcion, longitud, codigo_sunat)
    VALUES (p_descripcion, p_longitud, p_codigo_sunat);
END
$$

--
-- Create procedure `sp_tipos_documento_buscar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_documento_buscar (IN p_term varchar(100))
BEGIN
  SELECT
    id_tipo_documento,
    descripcion,
    longitud,
    codigo_sunat
  FROM tipos_documento
  WHERE descripcion LIKE CONCAT('%', p_term, '%')
  OR codigo_sunat LIKE CONCAT('%', p_term, '%')
  ORDER BY descripcion;
END
$$

--
-- Create procedure `sp_tipos_documento_actualizar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_documento_actualizar (IN p_id int,
IN p_descripcion varchar(50),
IN p_longitud int,
IN p_codigo_sunat varchar(2))
BEGIN
  UPDATE tipos_documento
  SET descripcion = p_descripcion,
      longitud = p_longitud,
      codigo_sunat = p_codigo_sunat
  WHERE id_tipo_documento = p_id;
END
$$

DELIMITER ;

--
-- Create table `profesores`
--
CREATE TABLE IF NOT EXISTS profesores (
  id_profesor int(11) NOT NULL AUTO_INCREMENT,
  id_tipo_documento int(11) NOT NULL,
  numero_documento varchar(20) NOT NULL,
  nombres varchar(100) NOT NULL,
  apellidos varchar(100) NOT NULL,
  email varchar(100) DEFAULT NULL,
  telefono varchar(20) DEFAULT NULL,
  especialidad varchar(255) DEFAULT NULL,
  PRIMARY KEY (id_profesor)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `documento_UNIQUE` on table `profesores`
--
ALTER TABLE profesores
ADD UNIQUE INDEX documento_UNIQUE (id_tipo_documento, numero_documento);

--
-- Create index `fk_profesores_tipos_documento_idx` on table `profesores`
--
ALTER TABLE profesores
ADD INDEX fk_profesores_tipos_documento_idx (id_tipo_documento);

--
-- Create foreign key
--
ALTER TABLE profesores
ADD CONSTRAINT fk_profesores_tipos_documento FOREIGN KEY (id_tipo_documento)
REFERENCES tipos_documento (id_tipo_documento) ON UPDATE CASCADE;

DELIMITER $$

--
-- Create procedure `sp_profesores_obtener_por_id`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_profesores_obtener_por_id (IN p_id int)
BEGIN
  SELECT
    id_profesor,
    id_tipo_documento,
    numero_documento,
    nombres,
    apellidos,
    email,
    telefono,
    especialidad
  FROM profesores
  WHERE id_profesor = p_id;
END
$$

--
-- Create procedure `sp_profesores_listar_simple`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_profesores_listar_simple ()
BEGIN
  SELECT
    id_profesor,
    CONCAT(apellidos, ', ', nombres) AS nombre_completo
  FROM profesores
  ORDER BY apellidos;
END
$$

--
-- Create procedure `sp_profesores_listar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_profesores_listar ()
BEGIN
  SELECT
    p.id_profesor,
    p.nombres,
    p.apellidos,
    p.email,
    p.telefono,
    p.especialidad,
    td.descripcion AS tipo_documento,
    p.numero_documento
  FROM profesores p
    JOIN tipos_documento td
      ON p.id_tipo_documento = td.id_tipo_documento
  ORDER BY p.apellidos, p.nombres;
END
$$

--
-- Create procedure `sp_profesores_eliminar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_profesores_eliminar (IN p_id int)
BEGIN
  -- Se podría añadir lógica para verificar dependencias antes de eliminar
  DELETE
    FROM profesores
  WHERE id_profesor = p_id;
END
$$

--
-- Create procedure `sp_profesores_crear`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_profesores_crear (IN p_id_tipo_documento int,
IN p_numero_documento varchar(20),
IN p_nombres varchar(100),
IN p_apellidos varchar(100),
IN p_email varchar(100),
IN p_telefono varchar(20),
IN p_especialidad varchar(255))
BEGIN
  INSERT INTO profesores (id_tipo_documento, numero_documento, nombres, apellidos, email, telefono, especialidad)
    VALUES (p_id_tipo_documento, p_numero_documento, p_nombres, p_apellidos, p_email, p_telefono, p_especialidad);
END
$$

--
-- Create procedure `sp_profesores_buscar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_profesores_buscar (IN p_termino varchar(100))
BEGIN
  SELECT
    id_profesor,
    CONCAT(nombres, ' ', apellidos) AS nombre_completo
  FROM profesores
  WHERE CONCAT(nombres, ' ', apellidos) LIKE CONCAT('%', p_termino, '%')
  ORDER BY apellidos, nombres
  LIMIT 10;
END
$$

--
-- Create procedure `sp_profesores_actualizar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_profesores_actualizar (IN p_id_profesor int,
IN p_id_tipo_documento int,
IN p_numero_documento varchar(20),
IN p_nombres varchar(100),
IN p_apellidos varchar(100),
IN p_email varchar(100),
IN p_telefono varchar(20),
IN p_especialidad varchar(255))
BEGIN
  UPDATE profesores
  SET id_tipo_documento = p_id_tipo_documento,
      numero_documento = p_numero_documento,
      nombres = p_nombres,
      apellidos = p_apellidos,
      email = p_email,
      telefono = p_telefono,
      especialidad = p_especialidad
  WHERE id_profesor = p_id_profesor;
END
$$

DELIMITER ;

--
-- Create table `clientes`
--
CREATE TABLE IF NOT EXISTS clientes (
  id_cliente int(11) NOT NULL AUTO_INCREMENT,
  id_tipo_documento int(11) NOT NULL,
  numero_documento varchar(20) NOT NULL,
  nombres varchar(100) NOT NULL,
  apellidos varchar(100) NOT NULL,
  email varchar(100) DEFAULT NULL,
  telefono varchar(20) DEFAULT NULL,
  codigo_erp varchar(20) DEFAULT NULL,
  fecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (id_cliente)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `documento_UNIQUE` on table `clientes`
--
ALTER TABLE clientes
ADD UNIQUE INDEX documento_UNIQUE (id_tipo_documento, numero_documento);

--
-- Create index `fk_clientes_tipos_documento_idx` on table `clientes`
--
ALTER TABLE clientes
ADD INDEX fk_clientes_tipos_documento_idx (id_tipo_documento);

--
-- Create foreign key
--
ALTER TABLE clientes
ADD CONSTRAINT fk_clientes_tipos_documento FOREIGN KEY (id_tipo_documento)
REFERENCES tipos_documento (id_tipo_documento) ON UPDATE CASCADE;

DELIMITER $$

--
-- Create procedure `sp_tipos_documento_verificar_dependencias`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_documento_verificar_dependencias (IN p_id_tipo_documento int)
BEGIN
  SELECT
    COUNT(id_cliente) AS count
  FROM clientes
  WHERE id_tipo_documento = p_id_tipo_documento;
END
$$

--
-- Create procedure `sp_clientes_obtener_por_id`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_clientes_obtener_por_id (IN p_id_cliente int)
BEGIN
  SELECT
    id_cliente,
    id_tipo_documento,
    numero_documento,
    nombres,
    apellidos,
    email,
    telefono,
    codigo_erp
  FROM clientes
  WHERE id_cliente = p_id_cliente;
END
$$

--
-- Create procedure `sp_clientes_listar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_clientes_listar ()
BEGIN
  SELECT
    c.id_cliente,
    c.nombres,
    c.apellidos,
    td.descripcion AS tipo_documento,
    c.numero_documento,
    c.email,
    c.telefono
  FROM clientes c
    JOIN tipos_documento td
      ON c.id_tipo_documento = td.id_tipo_documento
  ORDER BY c.apellidos, c.nombres;
END
$$

--
-- Create procedure `sp_clientes_eliminar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_clientes_eliminar (IN p_id_cliente int)
BEGIN
  DELETE
    FROM clientes
  WHERE id_cliente = p_id_cliente;
END
$$

--
-- Create procedure `sp_clientes_crear`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_clientes_crear (IN p_id_tipo_documento int,
IN p_numero_documento varchar(20),
IN p_nombres varchar(100),
IN p_apellidos varchar(100),
IN p_email varchar(100),
IN p_telefono varchar(20),
IN p_codigo_erp varchar(20))
BEGIN
  DECLARE cliente_existente int;

  SELECT
    COUNT(*) INTO cliente_existente
  FROM clientes
  WHERE id_tipo_documento = p_id_tipo_documento
  AND numero_documento = p_numero_documento;

  IF cliente_existente > 0 THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Ya existe un cliente con el mismo tipo y número de documento.';
  ELSE
    INSERT INTO clientes (id_tipo_documento, numero_documento, nombres, apellidos, email, telefono, codigo_erp)
      VALUES (p_id_tipo_documento, p_numero_documento, p_nombres, p_apellidos, p_email, p_telefono, p_codigo_erp);
    SELECT
      LAST_INSERT_ID() AS id_cliente;
  END IF;
END
$$

--
-- Create procedure `sp_clientes_buscar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_clientes_buscar (IN p_termino varchar(100))
BEGIN
  SET @termino_busqueda = CONCAT('%', p_termino, '%');
  SELECT
    c.id_cliente,
    c.nombres,
    c.apellidos,
    td.descripcion AS tipo_documento,
    c.numero_documento,
    c.email,
    c.telefono
  FROM clientes c
    JOIN tipos_documento td
      ON c.id_tipo_documento = td.id_tipo_documento
  WHERE c.nombres LIKE @termino_busqueda
  OR c.apellidos LIKE @termino_busqueda
  OR c.numero_documento LIKE @termino_busqueda
  ORDER BY c.apellidos, c.nombres;
END
$$

--
-- Create procedure `sp_clientes_actualizar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_clientes_actualizar (IN p_id_cliente int,
IN p_id_tipo_documento int,
IN p_numero_documento varchar(20),
IN p_nombres varchar(100),
IN p_apellidos varchar(100),
IN p_email varchar(100),
IN p_telefono varchar(20),
IN p_codigo_erp varchar(20))
BEGIN
  DECLARE cliente_existente int;
  SELECT
    COUNT(*) INTO cliente_existente
  FROM clientes
  WHERE id_tipo_documento = p_id_tipo_documento
  AND numero_documento = p_numero_documento
  AND id_cliente != p_id_cliente;

  IF cliente_existente > 0 THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El nuevo número de documento ya está en uso por otro cliente.';
  ELSE
    UPDATE clientes
    SET id_tipo_documento = p_id_tipo_documento,
        numero_documento = p_numero_documento,
        nombres = p_nombres,
        apellidos = p_apellidos,
        email = p_email,
        telefono = p_telefono,
        codigo_erp = p_codigo_erp
    WHERE id_cliente = p_id_cliente;
  END IF;
END
$$

--
-- Create procedure `sp_cliente_verificar_documento_existente`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_cliente_verificar_documento_existente (IN p_numero_documento varchar(20),
IN p_id_cliente_excluir int)
BEGIN
  SELECT
    COUNT(id_cliente) AS `exists`
  FROM clientes
  WHERE numero_documento = p_numero_documento
  AND (p_id_cliente_excluir IS NULL
  OR id_cliente != p_id_cliente_excluir);
END
$$

DELIMITER ;

--
-- Create table `formas_pago`
--
CREATE TABLE IF NOT EXISTS formas_pago (
  id_forma_pago int(11) NOT NULL AUTO_INCREMENT,
  nombre varchar(50) NOT NULL,
  PRIMARY KEY (id_forma_pago)
)
ENGINE = INNODB,
AUTO_INCREMENT = 9,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

DELIMITER $$

--
-- Create procedure `sp_formas_pago_obtener_por_id`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_formas_pago_obtener_por_id (IN p_id int)
BEGIN
  SELECT
    id_forma_pago,
    nombre
  FROM formas_pago
  WHERE id_forma_pago = p_id;
END
$$

--
-- Create procedure `sp_formas_pago_listar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_formas_pago_listar ()
BEGIN
  SELECT
    id_forma_pago,
    nombre
  FROM formas_pago
  ORDER BY nombre;
END
$$

--
-- Create procedure `sp_formas_pago_eliminar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_formas_pago_eliminar (IN p_id int)
BEGIN
  DELETE
    FROM formas_pago
  WHERE id_forma_pago = p_id;
END
$$

--
-- Create procedure `sp_formas_pago_crear`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_formas_pago_crear (IN p_nombre varchar(50))
BEGIN
  INSERT INTO formas_pago (nombre)
    VALUES (p_nombre);
END
$$

--
-- Create procedure `sp_formas_pago_buscar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_formas_pago_buscar (IN p_term varchar(100))
BEGIN
  SELECT
    id_forma_pago,
    nombre
  FROM formas_pago
  WHERE nombre LIKE CONCAT('%', p_term, '%')
  ORDER BY nombre;
END
$$

--
-- Create procedure `sp_formas_pago_actualizar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_formas_pago_actualizar (IN p_id int, IN p_nombre varchar(50))
BEGIN
  UPDATE formas_pago
  SET nombre = p_nombre
  WHERE id_forma_pago = p_id;
END
$$

DELIMITER ;

--
-- Create table `matriculas`
--
CREATE TABLE IF NOT EXISTS matriculas (
  id_matricula int(11) NOT NULL AUTO_INCREMENT,
  id_cliente int(11) NOT NULL,
  id_usuario_registro int(11) NOT NULL,
  id_forma_pago int(11) NOT NULL,
  fecha_matricula timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  fecha_inicio_clases date NOT NULL,
  fecha_fin_clases date NOT NULL,
  monto_total decimal(10, 2) NOT NULL,
  descuento_total decimal(10, 2) NOT NULL DEFAULT 0.00,
  monto_final decimal(10, 2) NOT NULL,
  observaciones text DEFAULT NULL,
  estado enum ('Activa', 'Completada', 'Anulada') NOT NULL DEFAULT 'Activa',
  PRIMARY KEY (id_matricula)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `fk_matriculas_cliente_idx` on table `matriculas`
--
ALTER TABLE matriculas
ADD INDEX fk_matriculas_cliente_idx (id_cliente);

--
-- Create index `fk_matriculas_usuario_idx` on table `matriculas`
--
ALTER TABLE matriculas
ADD INDEX fk_matriculas_usuario_idx (id_usuario_registro);

--
-- Create index `fk_matriculas_forma_pago_idx` on table `matriculas`
--
ALTER TABLE matriculas
ADD INDEX fk_matriculas_forma_pago_idx (id_forma_pago);

--
-- Create foreign key
--
ALTER TABLE matriculas
ADD CONSTRAINT fk_matriculas_cliente FOREIGN KEY (id_cliente)
REFERENCES clientes (id_cliente);

--
-- Create foreign key
--
ALTER TABLE matriculas
ADD CONSTRAINT fk_matriculas_forma_pago FOREIGN KEY (id_forma_pago)
REFERENCES formas_pago (id_forma_pago);

--
-- Create foreign key
--
ALTER TABLE matriculas
ADD CONSTRAINT fk_matriculas_usuario FOREIGN KEY (id_usuario_registro)
REFERENCES usuarios (id_usuario);

DELIMITER $$

--
-- Create procedure `sp_matriculas_listar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_matriculas_listar ()
BEGIN
  SELECT
    m.id_matricula,
    CONCAT(c.nombres, ' ', c.apellidos) AS nombre_cliente,
    m.fecha_matricula,
    m.monto_final,
    m.estado,
    u.nombre_usuario AS registrado_por
  FROM matriculas m
    JOIN clientes c
      ON m.id_cliente = c.id_cliente
    JOIN usuarios u
      ON m.id_usuario_registro = u.id_usuario
  ORDER BY m.fecha_matricula DESC;
END
$$

--
-- Create procedure `sp_matricula_registrar_cabecera`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_matricula_registrar_cabecera (IN p_id_cliente int,
IN p_id_usuario_registro int,
IN p_id_forma_pago int,
IN p_fecha_inicio_clases date,
IN p_fecha_fin_clases date,
IN p_monto_total decimal(10, 2),
IN p_descuento_total decimal(10, 2),
IN p_monto_final decimal(10, 2),
IN p_observaciones text)
BEGIN
  INSERT INTO matriculas (id_cliente, id_usuario_registro, id_forma_pago, fecha_inicio_clases, fecha_fin_clases, monto_total, descuento_total, monto_final, observaciones)
    VALUES (p_id_cliente, p_id_usuario_registro, p_id_forma_pago, p_fecha_inicio_clases, p_fecha_fin_clases, p_monto_total, p_descuento_total, p_monto_final, p_observaciones);
  SELECT
    LAST_INSERT_ID() AS id_matricula;
END
$$

--
-- Create procedure `sp_formas_pago_verificar_dependencias`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_formas_pago_verificar_dependencias (IN p_id_forma_pago int)
BEGIN
  SELECT
    COUNT(id_matricula) AS count
  FROM matriculas
  WHERE id_forma_pago = p_id_forma_pago;
END
$$

--
-- Create procedure `sp_dashboard_ventas_mensuales`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_dashboard_ventas_mensuales (IN p_anio int)
BEGIN
  SELECT
    MONTH(fecha_matricula) AS mes,
    SUM(monto_final) AS total_ventas
  FROM matriculas m
  WHERE YEAR(fecha_matricula) = p_anio
  GROUP BY MONTH(fecha_matricula)
  ORDER BY mes;
END
$$

--
-- Create procedure `sp_curso_verificar_dependencias`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_curso_verificar_dependencias (IN p_id_curso int)
BEGIN
  SELECT
    COUNT(id_matricula) AS count
  FROM matriculas
  WHERE id_curso = p_id_curso;
END
$$

--
-- Create procedure `sp_cliente_verificar_matriculas`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_cliente_verificar_matriculas (IN p_id_cliente int)
BEGIN
  SELECT
    COUNT(*) AS numero_matriculas
  FROM matriculas
  WHERE id_cliente = p_id_cliente;
END
$$

DELIMITER ;

--
-- Create table `tipos_curso`
--
CREATE TABLE IF NOT EXISTS tipos_curso (
  id_tipo_curso int(11) NOT NULL AUTO_INCREMENT,
  nombre varchar(50) NOT NULL,
  descripcion varchar(255) DEFAULT NULL,
  PRIMARY KEY (id_tipo_curso)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

DELIMITER $$

--
-- Create procedure `sp_tipos_curso_obtener_por_id`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_curso_obtener_por_id (IN p_id int)
BEGIN
  SELECT
    id_tipo_curso,
    nombre,
    descripcion
  FROM tipos_curso
  WHERE id_tipo_curso = p_id;
END
$$

--
-- Create procedure `sp_tipos_curso_listar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_curso_listar ()
BEGIN
  SELECT
    id_tipo_curso,
    nombre,
    descripcion
  FROM tipos_curso
  ORDER BY nombre;
END
$$

--
-- Create procedure `sp_tipos_curso_eliminar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_curso_eliminar (IN p_id int)
BEGIN
  DELETE
    FROM tipos_curso
  WHERE id_tipo_curso = p_id;
END
$$

--
-- Create procedure `sp_tipos_curso_crear`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_curso_crear (IN p_nombre varchar(50), IN p_descripcion varchar(255))
BEGIN
  INSERT INTO tipos_curso (nombre, descripcion)
    VALUES (p_nombre, p_descripcion);
END
$$

--
-- Create procedure `sp_tipos_curso_buscar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_curso_buscar (IN p_term varchar(100))
BEGIN
  SELECT
    id_tipo_curso,
    nombre,
    descripcion
  FROM tipos_curso
  WHERE nombre LIKE CONCAT('%', p_term, '%')
  OR descripcion LIKE CONCAT('%', p_term, '%')
  ORDER BY nombre;
END
$$

--
-- Create procedure `sp_tipos_curso_actualizar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_curso_actualizar (IN p_id int, IN p_nombre varchar(50), IN p_descripcion varchar(255))
BEGIN
  UPDATE tipos_curso
  SET nombre = p_nombre,
      descripcion = p_descripcion
  WHERE id_tipo_curso = p_id;
END
$$

DELIMITER ;

--
-- Create table `cursos`
--
CREATE TABLE IF NOT EXISTS cursos (
  id_curso int(11) NOT NULL AUTO_INCREMENT,
  id_tipo_curso int(11) NOT NULL,
  nombre varchar(150) NOT NULL,
  descripcion text DEFAULT NULL,
  codigo_erp varchar(20) DEFAULT NULL,
  PRIMARY KEY (id_curso)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `fk_cursos_tipos_curso_idx` on table `cursos`
--
ALTER TABLE cursos
ADD INDEX fk_cursos_tipos_curso_idx (id_tipo_curso);

--
-- Create foreign key
--
ALTER TABLE cursos
ADD CONSTRAINT fk_cursos_tipos_curso FOREIGN KEY (id_tipo_curso)
REFERENCES tipos_curso (id_tipo_curso) ON UPDATE CASCADE;

DELIMITER $$

--
-- Create procedure `sp_tipos_curso_verificar_dependencias`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_curso_verificar_dependencias (IN p_id_tipo_curso int)
BEGIN
  SELECT
    COUNT(id_curso) AS count
  FROM cursos
  WHERE id_tipo_curso = p_id_tipo_curso;
END
$$

--
-- Create procedure `sp_cursos_obtener_por_id`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_cursos_obtener_por_id (IN p_id int)
BEGIN
  SELECT
    id_curso,
    id_tipo_curso,
    nombre,
    descripcion,
    codigo_erp
  FROM cursos
  WHERE id_curso = p_id;
END
$$

--
-- Create procedure `sp_cursos_listar_simple`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_cursos_listar_simple ()
BEGIN
  SELECT
    id_curso,
    nombre
  FROM cursos
  ORDER BY nombre;
END
$$

--
-- Create procedure `sp_cursos_listar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_cursos_listar ()
BEGIN
  SELECT
    c.id_curso,
    c.nombre,
    c.descripcion,
    c.codigo_erp,
    tc.nombre AS tipo_curso
  FROM cursos c
    JOIN tipos_curso tc
      ON c.id_tipo_curso = tc.id_tipo_curso
  ORDER BY c.nombre;
END
$$

--
-- Create procedure `sp_cursos_eliminar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_cursos_eliminar (IN p_id int)
BEGIN
  DELETE
    FROM cursos
  WHERE id_curso = p_id;
END
$$

--
-- Create procedure `sp_cursos_crear`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_cursos_crear (IN p_id_tipo_curso int, IN p_nombre varchar(150), IN p_descripcion text, IN p_codigo_erp varchar(20))
BEGIN
  INSERT INTO cursos (id_tipo_curso, nombre, descripcion, codigo_erp)
    VALUES (p_id_tipo_curso, p_nombre, p_descripcion, p_codigo_erp);
END
$$

--
-- Create procedure `sp_cursos_buscar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_cursos_buscar (IN p_term varchar(100))
BEGIN
  SELECT
    c.id_curso,
    c.nombre,
    c.descripcion,
    c.codigo_erp,
    tc.nombre AS tipo_curso
  FROM cursos c
    JOIN tipos_curso tc
      ON c.id_tipo_curso = tc.id_tipo_curso
  WHERE c.nombre LIKE CONCAT('%', p_term, '%')
  OR c.descripcion LIKE CONCAT('%', p_term, '%')
  OR c.codigo_erp LIKE CONCAT('%', p_term, '%')
  ORDER BY c.nombre;
END
$$

--
-- Create procedure `sp_cursos_actualizar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_cursos_actualizar (IN p_id_curso int, IN p_id_tipo_curso int, IN p_nombre varchar(150), IN p_descripcion text, IN p_codigo_erp varchar(20))
BEGIN
  UPDATE cursos
  SET id_tipo_curso = p_id_tipo_curso,
      nombre = p_nombre,
      descripcion = p_descripcion,
      codigo_erp = p_codigo_erp
  WHERE id_curso = p_id_curso;
END
$$

DELIMITER ;

--
-- Create table `tipos_horario`
--
CREATE TABLE IF NOT EXISTS tipos_horario (
  id_tipo_horario int(11) NOT NULL AUTO_INCREMENT,
  descripcion varchar(100) NOT NULL,
  dias_semana varchar(20) NOT NULL COMMENT 'Ej: 1,3,5 para L,M,V (Lunes=1)',
  PRIMARY KEY (id_tipo_horario)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

DELIMITER $$

--
-- Create procedure `sp_tipos_horario_obtener_por_id`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_horario_obtener_por_id (IN p_id int)
BEGIN
  SELECT
    id_tipo_horario,
    descripcion,
    dias_semana
  FROM tipos_horario
  WHERE id_tipo_horario = p_id;
END
$$

--
-- Create procedure `sp_tipos_horario_listar_simple`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_horario_listar_simple ()
BEGIN
  SELECT
    id_tipo_horario,
    descripcion
  FROM tipos_horario
  ORDER BY descripcion;
END
$$

--
-- Create procedure `sp_tipos_horario_listar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_horario_listar ()
BEGIN
  SELECT
    id_tipo_horario,
    descripcion,
    dias_semana
  FROM tipos_horario
  ORDER BY descripcion;
END
$$

--
-- Create procedure `sp_tipos_horario_eliminar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_horario_eliminar (IN p_id int)
BEGIN
  DELETE
    FROM tipos_horario
  WHERE id_tipo_horario = p_id;
END
$$

--
-- Create procedure `sp_tipos_horario_crear`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_horario_crear (IN p_descripcion varchar(100), IN p_dias_semana varchar(20))
BEGIN
  INSERT INTO tipos_horario (descripcion, dias_semana)
    VALUES (p_descripcion, p_dias_semana);
END
$$

--
-- Create procedure `sp_tipos_horario_buscar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_horario_buscar (IN p_term varchar(100))
BEGIN
  SELECT
    id_tipo_horario,
    descripcion,
    dias_semana
  FROM tipos_horario
  WHERE descripcion LIKE CONCAT('%', p_term, '%')
  ORDER BY descripcion;
END
$$

--
-- Create procedure `sp_tipos_horario_actualizar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_horario_actualizar (IN p_id int, IN p_descripcion varchar(100), IN p_dias_semana varchar(20))
BEGIN
  UPDATE tipos_horario
  SET descripcion = p_descripcion,
      dias_semana = p_dias_semana
  WHERE id_tipo_horario = p_id;
END
$$

DELIMITER ;

--
-- Create table `cursos_programados`
--
CREATE TABLE IF NOT EXISTS cursos_programados (
  id_curso_programado int(11) NOT NULL AUTO_INCREMENT,
  id_curso int(11) NOT NULL,
  id_profesor int(11) NOT NULL,
  id_sub_area int(11) NOT NULL,
  id_tipo_horario int(11) NOT NULL,
  fecha_inicio date NOT NULL,
  fecha_fin date NOT NULL,
  hora_inicio time NOT NULL,
  hora_fin time NOT NULL,
  vacantes_disponibles int(11) NOT NULL,
  estado enum ('Programado', 'En Curso', 'Finalizado', 'Cancelado') NOT NULL DEFAULT 'Programado',
  PRIMARY KEY (id_curso_programado)
)
ENGINE = INNODB,
AUTO_INCREMENT = 11,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `fk_prog_curso_idx` on table `cursos_programados`
--
ALTER TABLE cursos_programados
ADD INDEX fk_prog_curso_idx (id_curso);

--
-- Create index `fk_prog_profesor_idx` on table `cursos_programados`
--
ALTER TABLE cursos_programados
ADD INDEX fk_prog_profesor_idx (id_profesor);

--
-- Create index `fk_prog_sub_area_idx` on table `cursos_programados`
--
ALTER TABLE cursos_programados
ADD INDEX fk_prog_sub_area_idx (id_sub_area);

--
-- Create index `fk_prog_tipo_horario_idx` on table `cursos_programados`
--
ALTER TABLE cursos_programados
ADD INDEX fk_prog_tipo_horario_idx (id_tipo_horario);

--
-- Create foreign key
--
ALTER TABLE cursos_programados
ADD CONSTRAINT fk_prog_curso FOREIGN KEY (id_curso)
REFERENCES cursos (id_curso);

--
-- Create foreign key
--
ALTER TABLE cursos_programados
ADD CONSTRAINT fk_prog_profesor FOREIGN KEY (id_profesor)
REFERENCES profesores (id_profesor);

--
-- Create foreign key
--
ALTER TABLE cursos_programados
ADD CONSTRAINT fk_prog_sub_area FOREIGN KEY (id_sub_area)
REFERENCES sub_areas (id_sub_area);

--
-- Create foreign key
--
ALTER TABLE cursos_programados
ADD CONSTRAINT fk_prog_tipo_horario FOREIGN KEY (id_tipo_horario)
REFERENCES tipos_horario (id_tipo_horario);

DELIMITER $$

--
-- Create procedure `sp_cursos_programados_por_profesor_en_rango`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_cursos_programados_por_profesor_en_rango (IN p_id_profesor int,
IN p_fecha_inicio date,
IN p_fecha_fin date,
IN p_id_curso_programado_excluir int)
BEGIN
  SELECT
    cp.id_curso_programado,
    cp.fecha_inicio,
    cp.fecha_fin,
    cp.hora_inicio,
    cp.hora_fin,
    th.dias_semana
  FROM cursos_programados cp
    JOIN tipos_horario th
      ON cp.id_tipo_horario = th.id_tipo_horario
  WHERE cp.id_profesor = p_id_profesor
  AND cp.fecha_inicio <= p_fecha_fin
  AND cp.fecha_fin >= p_fecha_inicio
  AND (p_id_curso_programado_excluir IS NULL
  OR cp.id_curso_programado != p_id_curso_programado_excluir);
END
$$

--
-- Create procedure `sp_cursos_programados_obtener_por_id`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_cursos_programados_obtener_por_id (IN p_id int)
BEGIN
  SELECT
    id_curso_programado,
    id_curso,
    id_profesor,
    id_sub_area,
    id_tipo_horario,
    fecha_inicio,
    fecha_fin,
    hora_inicio,
    hora_fin,
    vacantes_disponibles AS vacantes
  FROM cursos_programados
  WHERE id_curso_programado = p_id;
END
$$

--
-- Create procedure `sp_cursos_programados_listar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_cursos_programados_listar (IN p_id_profesor int,
IN p_id_curso int,
IN p_fecha_inicio date,
IN p_fecha_fin date)
BEGIN
  SELECT
    cp.id_curso_programado,
    c.nombre AS curso_nombre,
    CONCAT(p.nombres, ' ', p.apellidos) AS profesor_nombre,
    CONCAT(a.nombre, ' - ', sa.descripcion, ' ', sa.numero_sub_area) AS ubicacion,
    th.descripcion AS tipo_horario_nombre,
    cp.fecha_inicio,
    cp.fecha_fin,
    cp.hora_inicio,
    cp.hora_fin,
    cp.estado
  FROM cursos_programados cp
    JOIN cursos c
      ON cp.id_curso = c.id_curso
    JOIN profesores p
      ON cp.id_profesor = p.id_profesor
    JOIN tipos_horario th
      ON cp.id_tipo_horario = th.id_tipo_horario
    JOIN sub_areas sa
      ON cp.id_sub_area = sa.id_sub_area
    JOIN areas a
      ON sa.id_area = a.id_area
  WHERE (p_id_profesor IS NULL
  OR cp.id_profesor = p_id_profesor)
  AND (p_id_curso IS NULL
  OR cp.id_curso = p_id_curso)
  AND (p_fecha_inicio IS NULL
  OR cp.fecha_inicio >= p_fecha_inicio)
  AND (p_fecha_fin IS NULL
  OR cp.fecha_fin <= p_fecha_fin)
  ORDER BY cp.fecha_inicio DESC;
END
$$

--
-- Create procedure `sp_cursos_programados_crear`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_cursos_programados_crear (IN p_id_curso int,
IN p_id_profesor int,
IN p_id_sub_area int,
IN p_id_tipo_horario int,
IN p_fecha_inicio date,
IN p_fecha_fin date,
IN p_hora_inicio time,
IN p_hora_fin time,
IN p_vacantes int)
BEGIN
  -- Obtenemos la capacidad de la sub-área para validar las vacantes
  DECLARE v_capacidad int;
  SELECT
    capacidad_maxima INTO v_capacidad
  FROM sub_areas
  WHERE id_sub_area = p_id_sub_area;

  IF p_vacantes > v_capacidad THEN
    SET p_vacantes = v_capacidad;
  END IF;

  INSERT INTO cursos_programados (id_curso, id_profesor, id_sub_area, id_tipo_horario, fecha_inicio, fecha_fin, hora_inicio, hora_fin, vacantes_disponibles)
    VALUES (p_id_curso, p_id_profesor, p_id_sub_area, p_id_tipo_horario, p_fecha_inicio, p_fecha_fin, p_hora_inicio, p_hora_fin, p_vacantes);

  SELECT
    LAST_INSERT_ID() AS id_curso_programado;
END
$$

--
-- Create procedure `sp_cursos_programados_actualizar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_cursos_programados_actualizar (IN p_id_curso_programado int,
IN p_id_curso int,
IN p_id_profesor int,
IN p_id_sub_area int,
IN p_id_tipo_horario int,
IN p_fecha_inicio date,
IN p_fecha_fin date,
IN p_hora_inicio time,
IN p_hora_fin time,
IN p_vacantes int)
BEGIN
  -- Se podría añadir lógica para no permitir la edición si el curso ya tiene matrículas,
  -- pero por ahora se mantiene simple.
  UPDATE cursos_programados
  SET id_curso = p_id_curso,
      id_profesor = p_id_profesor,
      id_sub_area = p_id_sub_area,
      id_tipo_horario = p_id_tipo_horario,
      fecha_inicio = p_fecha_inicio,
      fecha_fin = p_fecha_fin,
      hora_inicio = p_hora_inicio,
      hora_fin = p_hora_fin,
      vacantes_disponibles = p_vacantes
  WHERE id_curso_programado = p_id_curso_programado;
END
$$

--
-- Create procedure `sp_asistencia_profesor_obtener_detalle_curso`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_asistencia_profesor_obtener_detalle_curso (IN p_id_curso_programado int)
BEGIN
  SELECT
    c.nombre AS curso_nombre,
    CONCAT(p.nombres, ' ', p.apellidos) AS profesor_nombre,
    CONCAT(a.nombre, ' - ', sa.descripcion, ' ', sa.numero_sub_area) AS ubicacion,
    th.descripcion AS tipo_horario_nombre,
    cp.fecha_inicio,
    cp.fecha_fin,
    cp.hora_inicio,
    cp.hora_fin
  FROM cursos_programados cp
    JOIN cursos c
      ON cp.id_curso = c.id_curso
    JOIN profesores p
      ON cp.id_profesor = p.id_profesor
    JOIN sub_areas sa
      ON cp.id_sub_area = sa.id_sub_area
    JOIN areas a
      ON sa.id_area = a.id_area
    JOIN tipos_horario th
      ON cp.id_tipo_horario = th.id_tipo_horario
  WHERE cp.id_curso_programado = p_id_curso_programado;
END
$$

--
-- Create procedure `sp_asistencia_profesor_listar_cursos`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_asistencia_profesor_listar_cursos (IN p_id_profesor int,
IN p_id_curso int,
IN p_fecha_inicio date,
IN p_fecha_fin date)
BEGIN
  SELECT
    cp.id_curso_programado,
    c.nombre AS curso_nombre,
    CONCAT(p.nombres, ' ', p.apellidos) AS profesor_nombre,
    cp.fecha_inicio,
    cp.fecha_fin,
    th.descripcion AS dias,
    CONCAT(TIME_FORMAT(cp.hora_inicio, '%h:%i %p'), ' - ', TIME_FORMAT(cp.hora_fin, '%h:%i %p')) AS horas,
    CONCAT(a.nombre, ' - ', sa.descripcion, ' ', sa.numero_sub_area) AS ubicacion,
    cp.estado
  FROM cursos_programados cp
    JOIN cursos c
      ON cp.id_curso = c.id_curso
    JOIN profesores p
      ON cp.id_profesor = p.id_profesor
    JOIN tipos_horario th
      ON cp.id_tipo_horario = th.id_tipo_horario
    JOIN sub_areas sa
      ON cp.id_sub_area = sa.id_sub_area
    JOIN areas a
      ON sa.id_area = a.id_area
  WHERE (p_id_profesor IS NULL
  OR cp.id_profesor = p_id_profesor)
  AND (p_id_curso IS NULL
  OR cp.id_curso = p_id_curso)
  AND (p_fecha_inicio IS NULL
  OR cp.fecha_inicio >= p_fecha_inicio)
  AND (p_fecha_fin IS NULL
  OR cp.fecha_fin <= p_fecha_fin)
  ORDER BY cp.fecha_inicio DESC;
END
$$

DELIMITER ;

--
-- Create table `matriculas_detalle`
--
CREATE TABLE IF NOT EXISTS matriculas_detalle (
  id_matricula_detalle int(11) NOT NULL AUTO_INCREMENT,
  id_matricula int(11) NOT NULL,
  id_curso_programado int(11) NOT NULL,
  id_cliente_asistencia int(11) DEFAULT NULL,
  precio_pactado decimal(10, 2) NOT NULL,
  descuento decimal(10, 2) NOT NULL DEFAULT 0.00,
  precio_final decimal(10, 2) NOT NULL,
  PRIMARY KEY (id_matricula_detalle)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `fk_detalle_matricula_idx` on table `matriculas_detalle`
--
ALTER TABLE matriculas_detalle
ADD INDEX fk_detalle_matricula_idx (id_matricula);

--
-- Create index `fk_detalle_curso_prog_idx` on table `matriculas_detalle`
--
ALTER TABLE matriculas_detalle
ADD INDEX fk_detalle_curso_prog_idx (id_curso_programado);

--
-- Create index `fk_detalle_cliente_asistencia_idx` on table `matriculas_detalle`
--
ALTER TABLE matriculas_detalle
ADD INDEX fk_detalle_cliente_asistencia_idx (id_cliente_asistencia);

--
-- Create foreign key
--
ALTER TABLE matriculas_detalle
ADD CONSTRAINT fk_detalle_cliente_asistencia FOREIGN KEY (id_cliente_asistencia)
REFERENCES clientes (id_cliente) ON DELETE SET NULL ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE matriculas_detalle
ADD CONSTRAINT fk_detalle_curso_prog FOREIGN KEY (id_curso_programado)
REFERENCES cursos_programados (id_curso_programado);

--
-- Create foreign key
--
ALTER TABLE matriculas_detalle
ADD CONSTRAINT fk_detalle_matricula FOREIGN KEY (id_matricula)
REFERENCES matriculas (id_matricula) ON DELETE CASCADE;

DELIMITER $$

--
-- Create procedure `sp_matricula_registrar_detalle`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_matricula_registrar_detalle (IN p_id_matricula int,
IN p_id_curso_programado int,
IN p_id_cliente_asistencia int, -- Nuevo parámetro
IN p_precio_pactado decimal(10, 2),
IN p_descuento decimal(10, 2),
IN p_precio_final decimal(10, 2))
BEGIN
  DECLARE v_vacantes int;
  -- Verificar vacantes
  SELECT
    vacantes_disponibles INTO v_vacantes
  FROM cursos_programados
  WHERE id_curso_programado = p_id_curso_programado;
  IF v_vacantes > 0 THEN
    -- Insertar detalle
    INSERT INTO matriculas_detalle (id_matricula, id_curso_programado, id_cliente_asistencia, precio_pactado, descuento, precio_final)
      VALUES (p_id_matricula, p_id_curso_programado, p_id_cliente_asistencia, p_precio_pactado, p_descuento, p_precio_final);
    -- Actualizar vacantes
    UPDATE cursos_programados
    SET vacantes_disponibles = vacantes_disponibles - 1
    WHERE id_curso_programado = p_id_curso_programado;
    SELECT
      LAST_INSERT_ID() AS id_matricula_detalle;
  ELSE
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'No hay vacantes disponibles para este curso.';
  END IF;
END
$$

--
-- Create procedure `sp_dashboard_ventas_por_curso`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_dashboard_ventas_por_curso (IN p_anio int,
IN p_mes int)
BEGIN
  SELECT
    c.nombre AS nombre_curso,
    SUM(md.precio_final) AS total_ventas
  FROM matriculas_detalle md
    JOIN matriculas m
      ON md.id_matricula = m.id_matricula
    JOIN cursos_programados cp
      ON md.id_curso_programado = cp.id_curso_programado
    JOIN cursos c
      ON cp.id_curso = c.id_curso
  WHERE YEAR(m.fecha_matricula) = p_anio
  AND MONTH(m.fecha_matricula) = p_mes
  GROUP BY c.nombre
  ORDER BY total_ventas DESC;
END
$$

DELIMITER ;

--
-- Create table `asistencia_cliente`
--
CREATE TABLE IF NOT EXISTS asistencia_cliente (
  id_asistencia_cliente int(11) NOT NULL AUTO_INCREMENT,
  id_matricula_detalle int(11) NOT NULL,
  id_cliente int(11) NOT NULL,
  fecha_clase date NOT NULL,
  estado enum ('Programado', 'Asistió', 'Faltó', 'Justificado', 'Postergado') NOT NULL DEFAULT 'Programado',
  observaciones varchar(255) DEFAULT NULL,
  PRIMARY KEY (id_asistencia_cliente)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `fk_asist_cli_matricula_det_idx` on table `asistencia_cliente`
--
ALTER TABLE asistencia_cliente
ADD INDEX fk_asist_cli_matricula_det_idx (id_matricula_detalle);

--
-- Create index `fk_asist_cli_cliente_idx` on table `asistencia_cliente`
--
ALTER TABLE asistencia_cliente
ADD INDEX fk_asist_cli_cliente_idx (id_cliente);

--
-- Create foreign key
--
ALTER TABLE asistencia_cliente
ADD CONSTRAINT fk_asist_cli_cliente FOREIGN KEY (id_cliente)
REFERENCES clientes (id_cliente);

--
-- Create foreign key
--
ALTER TABLE asistencia_cliente
ADD CONSTRAINT fk_asist_cli_matricula_det FOREIGN KEY (id_matricula_detalle)
REFERENCES matriculas_detalle (id_matricula_detalle);

DELIMITER $$

--
-- Create procedure `sp_matricula_anular`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_matricula_anular (IN p_id_matricula int,
IN p_observaciones text)
BEGIN
  DECLARE v_estado_actual varchar(20);

  -- Iniciar transacción
  START TRANSACTION;

    -- Verificar que la matrícula no esté ya anulada
    SELECT
      estado INTO v_estado_actual
    FROM matriculas
    WHERE id_matricula = p_id_matricula;

    IF v_estado_actual = 'Activa' THEN
      -- 1. Actualizar el estado de la matrícula y añadir la observación
      UPDATE matriculas
      SET estado = 'Anulada',
          observaciones = CONCAT(IFNULL(observaciones, ''), '\nANULACIÓN: ', p_observaciones)
      WHERE id_matricula = p_id_matricula;

      -- 2. Devolver las vacantes de los cursos asociados a esta matrícula
      UPDATE cursos_programados cp
      JOIN matriculas_detalle md
        ON cp.id_curso_programado = md.id_curso_programado
      SET cp.vacantes_disponibles = cp.vacantes_disponibles + 1
      WHERE md.id_matricula = p_id_matricula;

      -- 3. Opcional: Cambiar el estado de la asistencia del cliente a 'Cancelado'
      UPDATE asistencia_cliente ac
      JOIN matriculas_detalle md
        ON ac.id_matricula_detalle = md.id_matricula_detalle
      SET ac.estado = 'Cancelado'
      WHERE md.id_matricula = p_id_matricula;

      COMMIT;
    ELSE
      -- Si ya está anulada o completada, no hacer nada y revertir
      ROLLBACK;
      SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'La matrícula no se puede anular porque no está activa.';
    END IF;
END
$$

--
-- Create procedure `sp_asistencia_cliente_generar_cronograma`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_asistencia_cliente_generar_cronograma (IN p_id_matricula_detalle int)
BEGIN
  DECLARE v_fecha_actual date;
  DECLARE v_fecha_fin date;
  DECLARE v_id_cliente int;
  DECLARE v_id_curso_programado int;
  DECLARE v_dias_semana varchar(20);

  -- Obtener datos de la programación y el cliente de asistencia
  SELECT
    cp.fecha_inicio,
    cp.fecha_fin,
    md.id_cliente_asistencia,
    cp.id_curso_programado,
    th.dias_semana INTO v_fecha_actual, v_fecha_fin, v_id_cliente, v_id_curso_programado, v_dias_semana
  FROM matriculas_detalle md
    JOIN cursos_programados cp
      ON md.id_curso_programado = cp.id_curso_programado
    JOIN tipos_horario th
      ON cp.id_tipo_horario = th.id_tipo_horario
  WHERE md.id_matricula_detalle = p_id_matricula_detalle;

  -- Solo generar si hay un cliente de asistencia asignado
  IF v_id_cliente IS NOT NULL THEN
    -- Limpiar cronograma existente por si se regenera
    DELETE
      FROM asistencia_cliente
    WHERE id_matricula_detalle = p_id_matricula_detalle;

    -- Bucle para generar registros de asistencia
    WHILE v_fecha_actual <= v_fecha_fin DO
      IF FIND_IN_SET(WEEKDAY(v_fecha_actual) + 1, v_dias_semana COLLATE utf8mb4_unicode_ci) THEN
        INSERT INTO asistencia_cliente (id_matricula_detalle, id_cliente, fecha_clase, estado)
          VALUES (p_id_matricula_detalle, v_id_cliente, v_fecha_actual, 'Programado');
      END IF;
      SET v_fecha_actual = DATE_ADD(v_fecha_actual, INTERVAL 1 DAY);
    END WHILE;
  END IF;
END
$$

DELIMITER ;

--
-- Create table `asistencia_profesor`
--
CREATE TABLE IF NOT EXISTS asistencia_profesor (
  id_asistencia_profesor int(11) NOT NULL AUTO_INCREMENT,
  id_curso_programado int(11) NOT NULL,
  id_profesor int(11) NOT NULL,
  fecha_clase date NOT NULL,
  estado enum ('Programado', 'Asistió', 'Faltó', 'Reprogramado') NOT NULL DEFAULT 'Programado',
  observaciones varchar(255) DEFAULT NULL,
  PRIMARY KEY (id_asistencia_profesor)
)
ENGINE = INNODB,
AUTO_INCREMENT = 328,
AVG_ROW_LENGTH = 315,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `fk_asist_prof_curso_prog_idx` on table `asistencia_profesor`
--
ALTER TABLE asistencia_profesor
ADD INDEX fk_asist_prof_curso_prog_idx (id_curso_programado);

--
-- Create index `fk_asist_prof_profesor_idx` on table `asistencia_profesor`
--
ALTER TABLE asistencia_profesor
ADD INDEX fk_asist_prof_profesor_idx (id_profesor);

--
-- Create foreign key
--
ALTER TABLE asistencia_profesor
ADD CONSTRAINT fk_asist_prof_curso_prog FOREIGN KEY (id_curso_programado)
REFERENCES cursos_programados (id_curso_programado);

--
-- Create foreign key
--
ALTER TABLE asistencia_profesor
ADD CONSTRAINT fk_asist_prof_profesor FOREIGN KEY (id_profesor)
REFERENCES profesores (id_profesor);

DELIMITER $$

--
-- Create procedure `sp_cursos_programados_eliminar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_cursos_programados_eliminar (IN p_id int)
BEGIN
  -- Idealmente, verificar si hay matrículas asociadas antes de eliminar.
  -- Si se elimina, también se deberían limpiar las asistencias generadas.
  DELETE
    FROM asistencia_profesor
  WHERE id_curso_programado = p_id;
  DELETE
    FROM cursos_programados
  WHERE id_curso_programado = p_id;
END
$$

--
-- Create procedure `sp_asistencia_profesor_obtener_clases`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_asistencia_profesor_obtener_clases (IN p_id_curso_programado int,
IN p_limit int,
IN p_offset int)
BEGIN
  SELECT
    id_asistencia_profesor,
    fecha_clase,
    estado,
    observaciones
  FROM asistencia_profesor
  WHERE id_curso_programado = p_id_curso_programado
  ORDER BY fecha_clase ASC
  LIMIT p_limit OFFSET p_offset;
END
$$

--
-- Create procedure `sp_asistencia_profesor_generar_cronograma`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_asistencia_profesor_generar_cronograma (IN p_id_curso_programado int)
BEGIN
  DECLARE v_fecha_actual date;
  DECLARE v_fecha_fin date;
  DECLARE v_id_profesor int;
  DECLARE v_dias_semana varchar(20);

  -- Obtener datos de la programación
  SELECT
    fecha_inicio,
    fecha_fin,
    id_profesor,
    th.dias_semana INTO v_fecha_actual, v_fecha_fin, v_id_profesor, v_dias_semana
  FROM cursos_programados cp
    JOIN tipos_horario th
      ON cp.id_tipo_horario = th.id_tipo_horario
  WHERE cp.id_curso_programado = p_id_curso_programado;

  -- Limpiar cronograma existente por si se regenera
  DELETE
    FROM asistencia_profesor
  WHERE id_curso_programado = p_id_curso_programado;

  -- Bucle para generar registros de asistencia
  WHILE v_fecha_actual <= v_fecha_fin DO
    -- WEEKDAY() devuelve 0 para Lunes, 1 para Martes, etc. Se suma 1 para alinear con el formato guardado (Lunes=1, etc.)
    -- Se inserta si el día de la semana está en la cadena de días permitidos
    -- Se usa COLLATE para forzar la codificación correcta y evitar errores
    IF FIND_IN_SET(WEEKDAY(v_fecha_actual) + 1, v_dias_semana COLLATE utf8mb4_unicode_ci) THEN
      INSERT INTO asistencia_profesor (id_curso_programado, id_profesor, fecha_clase, estado)
        VALUES (p_id_curso_programado, v_id_profesor, v_fecha_actual, 'Programado');
    END IF;
    SET v_fecha_actual = DATE_ADD(v_fecha_actual, INTERVAL 1 DAY);
  END WHILE;
END
$$

--
-- Create procedure `sp_asistencia_profesor_contar_clases`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_asistencia_profesor_contar_clases (IN p_id_curso_programado int)
BEGIN
  SELECT
    COUNT(id_asistencia_profesor) AS total
  FROM asistencia_profesor
  WHERE id_curso_programado = p_id_curso_programado;
END
$$

--
-- Create procedure `sp_asistencia_profesor_actualizar_asistencia`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_asistencia_profesor_actualizar_asistencia (IN p_id_asistencia_profesor int,
IN p_estado enum ('Programado', 'Asistió', 'Faltó', 'Reprogramado'),
IN p_observaciones varchar(255))
BEGIN
  UPDATE asistencia_profesor
  SET estado = p_estado,
      observaciones = p_observaciones
  WHERE id_asistencia_profesor = p_id_asistencia_profesor;
END
$$

DELIMITER ;

--
-- Create table `tipos_precio`
--
CREATE TABLE IF NOT EXISTS tipos_precio (
  id_tipo_precio int(11) NOT NULL AUTO_INCREMENT,
  nombre varchar(50) NOT NULL,
  PRIMARY KEY (id_tipo_precio)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

DELIMITER $$

--
-- Create procedure `sp_tipos_precio_obtener_por_id`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_precio_obtener_por_id (IN p_id int)
BEGIN
  SELECT
    id_tipo_precio,
    nombre
  FROM tipos_precio
  WHERE id_tipo_precio = p_id;
END
$$

--
-- Create procedure `sp_tipos_precio_listar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_precio_listar ()
BEGIN
  SELECT
    id_tipo_precio,
    nombre
  FROM tipos_precio
  ORDER BY nombre;
END
$$

--
-- Create procedure `sp_tipos_precio_eliminar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_precio_eliminar (IN p_id int)
BEGIN
  DELETE
    FROM tipos_precio
  WHERE id_tipo_precio = p_id;
END
$$

--
-- Create procedure `sp_tipos_precio_crear`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_precio_crear (IN p_nombre varchar(50))
BEGIN
  INSERT INTO tipos_precio (nombre)
    VALUES (p_nombre);
END
$$

--
-- Create procedure `sp_tipos_precio_buscar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_precio_buscar (IN p_term varchar(100))
BEGIN
  SELECT
    id_tipo_precio,
    nombre
  FROM tipos_precio
  WHERE nombre LIKE CONCAT('%', p_term, '%')
  ORDER BY nombre;
END
$$

--
-- Create procedure `sp_tipos_precio_actualizar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_precio_actualizar (IN p_id int, IN p_nombre varchar(50))
BEGIN
  UPDATE tipos_precio
  SET nombre = p_nombre
  WHERE id_tipo_precio = p_id;
END
$$

DELIMITER ;

--
-- Create table `lista_precios`
--
CREATE TABLE IF NOT EXISTS lista_precios (
  id_lista_precio int(11) NOT NULL AUTO_INCREMENT,
  id_curso int(11) NOT NULL,
  id_tipo_precio int(11) NOT NULL,
  precio decimal(10, 2) NOT NULL,
  vigencia_inicio date NOT NULL,
  vigencia_fin date NOT NULL,
  PRIMARY KEY (id_lista_precio)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create index `fk_precios_curso_idx` on table `lista_precios`
--
ALTER TABLE lista_precios
ADD INDEX fk_precios_curso_idx (id_curso);

--
-- Create index `fk_precios_tipo_precio_idx` on table `lista_precios`
--
ALTER TABLE lista_precios
ADD INDEX fk_precios_tipo_precio_idx (id_tipo_precio);

--
-- Create foreign key
--
ALTER TABLE lista_precios
ADD CONSTRAINT fk_precios_curso FOREIGN KEY (id_curso)
REFERENCES cursos (id_curso);

--
-- Create foreign key
--
ALTER TABLE lista_precios
ADD CONSTRAINT fk_precios_tipo_precio FOREIGN KEY (id_tipo_precio)
REFERENCES tipos_precio (id_tipo_precio);

DELIMITER $$

--
-- Create procedure `sp_tipos_precio_verificar_dependencias`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_precio_verificar_dependencias (IN p_id_tipo_precio int)
BEGIN
  SELECT
    COUNT(id_lista_precio) AS count
  FROM lista_precios
  WHERE id_tipo_precio = p_id_tipo_precio;
END
$$

--
-- Create procedure `sp_lista_precios_obtener_por_id`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_lista_precios_obtener_por_id (IN p_id int)
BEGIN
  SELECT
    id_lista_precio,
    id_curso,
    id_tipo_precio,
    precio,
    vigencia_inicio,
    vigencia_fin
  FROM lista_precios
  WHERE id_lista_precio = p_id;
END
$$

--
-- Create procedure `sp_lista_precios_listar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_lista_precios_listar ()
BEGIN
  SELECT
    lp.id_lista_precio,
    c.nombre AS curso_nombre,
    tp.nombre AS tipo_precio_nombre,
    lp.precio,
    lp.vigencia_inicio,
    lp.vigencia_fin
  FROM lista_precios lp
    JOIN cursos c
      ON lp.id_curso = c.id_curso
    JOIN tipos_precio tp
      ON lp.id_tipo_precio = tp.id_tipo_precio
  ORDER BY c.nombre, lp.vigencia_inicio;
END
$$

--
-- Create procedure `sp_lista_precios_eliminar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_lista_precios_eliminar (IN p_id int)
BEGIN
  DELETE
    FROM lista_precios
  WHERE id_lista_precio = p_id;
END
$$

--
-- Create procedure `sp_lista_precios_crear`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_lista_precios_crear (IN p_id_curso int,
IN p_id_tipo_precio int,
IN p_precio decimal(10, 2),
IN p_vigencia_inicio date,
IN p_vigencia_fin date)
BEGIN
  INSERT INTO lista_precios (id_curso, id_tipo_precio, precio, vigencia_inicio, vigencia_fin)
    VALUES (p_id_curso, p_id_tipo_precio, p_precio, p_vigencia_inicio, p_vigencia_fin);
END
$$

--
-- Create procedure `sp_lista_precios_buscar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_lista_precios_buscar (IN p_term varchar(100))
BEGIN
  SELECT
    lp.id_lista_precio,
    c.nombre AS curso_nombre,
    tp.nombre AS tipo_precio_nombre,
    lp.precio,
    lp.vigencia_inicio,
    lp.vigencia_fin
  FROM lista_precios lp
    JOIN cursos c
      ON lp.id_curso = c.id_curso
    JOIN tipos_precio tp
      ON lp.id_tipo_precio = tp.id_tipo_precio
  WHERE c.nombre LIKE CONCAT('%', p_term, '%')
  OR tp.nombre LIKE CONCAT('%', p_term, '%')
  ORDER BY c.nombre, lp.vigencia_inicio;
END
$$

--
-- Create procedure `sp_lista_precios_actualizar`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_lista_precios_actualizar (IN p_id_lista_precio int,
IN p_id_curso int,
IN p_id_tipo_precio int,
IN p_precio decimal(10, 2),
IN p_vigencia_inicio date,
IN p_vigencia_fin date)
BEGIN
  UPDATE lista_precios
  SET id_curso = p_id_curso,
      id_tipo_precio = p_id_tipo_precio,
      precio = p_precio,
      vigencia_inicio = p_vigencia_inicio,
      vigencia_fin = p_vigencia_fin
  WHERE id_lista_precio = p_id_lista_precio;
END
$$

--
-- Create procedure `sp_cursos_programados_buscar_disponibles`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_cursos_programados_buscar_disponibles (IN p_profesor_id int,
IN p_fecha_inicio date,
IN p_fecha_fin date)
BEGIN
  SELECT
    cp.id_curso_programado,
    c.nombre AS nombre_curso,
    c.descripcion AS curso_descripcion,
    CONCAT(p.nombres, ' ', p.apellidos) AS nombre_profesor,
    a.nombre AS area,
    sa.descripcion AS sub_area,
    sa.numero_sub_area,
    cp.fecha_inicio,
    cp.fecha_fin,
    cp.hora_inicio,
    cp.hora_fin,
    th.descripcion AS horario_dias,
    cp.vacantes_disponibles,
    (SELECT
        lp.precio
      FROM lista_precios lp
      WHERE lp.id_curso = c.id_curso
      AND cp.fecha_inicio BETWEEN lp.vigencia_inicio AND lp.vigencia_fin
      ORDER BY lp.id_tipo_precio LIMIT 1) AS precio_actual
  FROM cursos_programados cp
    JOIN cursos c
      ON cp.id_curso = c.id_curso
    JOIN profesores p
      ON cp.id_profesor = p.id_profesor
    JOIN sub_areas sa
      ON cp.id_sub_area = sa.id_sub_area
    JOIN areas a
      ON sa.id_area = a.id_area
    JOIN tipos_horario th
      ON cp.id_tipo_horario = th.id_tipo_horario
  WHERE cp.vacantes_disponibles > 0
  AND cp.estado = 'Programado'
  AND (p_profesor_id IS NULL
  OR cp.id_profesor = p_profesor_id)
  AND (p_fecha_inicio IS NULL
  OR cp.fecha_inicio >= p_fecha_inicio)
  AND (p_fecha_fin IS NULL
  OR cp.fecha_fin <= p_fecha_fin)
  ORDER BY cp.fecha_inicio;
END
$$

--
-- Create procedure `sp_tipos_horario_verificar_dependencias`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_tipos_horario_verificar_dependencias (IN p_id_tipo_horario int)
BEGIN
  SELECT
    COUNT(id_programacion) AS count
  FROM programacion_horarios
  WHERE id_tipo_horario = p_id_tipo_horario;
END
$$

--
-- Create procedure `sp_sub_areas_verificar_dependencias`
--
CREATE
DEFINER = 'miguel'@'localhost'
PROCEDURE IF NOT EXISTS sp_sub_areas_verificar_dependencias (IN p_id_sub_area int)
BEGIN
  SELECT
    COUNT(id_programacion) AS count
  FROM programacion_horarios
  WHERE id_sub_area = p_id_sub_area;
END
$$

DELIMITER ;

-- 
-- Dumping data for table tipos_area
--
INSERT INTO tipos_area VALUES
(9, 'PISCINA'),
(10, 'GIMNASIO');

-- 
-- Dumping data for table roles
--
INSERT INTO roles VALUES
(1, 'Administrador', 'Acceso total al sistema'),
(2, 'Usuario', 'Acceso limitado a operaciones');

-- 
-- Dumping data for table tipos_documento
--
INSERT INTO tipos_documento VALUES
(1, 'DNI', 8, '1'),
(2, 'Pasaporte', 12, '7'),
(3, 'Carnet de Extranjería', 12, '4');

-- 
-- Dumping data for table areas
--
INSERT INTO areas VALUES
(2, 9, 'PISCINA MEDIANA'),
(5, 9, 'PISCINA GRANDE'),
(6, 9, 'PISCINA PEQUEÑA'),
(7, 10, 'GIMNASIO');

-- 
-- Dumping data for table usuarios
--
INSERT INTO usuarios VALUES
(1, 1, 'admin', '$2y$10$L1S.x6ysYw85etBL0S2IaOOwz0oWlAoio.tQH71HIVBzlSzY9vVMu', 'soporte@codesicorp.com', 'Administrador del Sistema', 1, '2025-09-01 18:49:46', '244713', '2025-09-03 07:59:10'),
(3, 2, 'prueba', '$2y$10$XcxywyUzZAnEZM.r/5T1M.JEcxKiVP1U5p7WhnllfUd6CWAQ7D2DC', 'santiago@codesicorp.com', 'prueba2', 1, '2025-09-02 23:28:23', '780141', '2025-09-03 00:00:54');

-- 
-- Dumping data for table formas_pago
--
INSERT INTO formas_pago VALUES
(1, 'Efectivo'),
(3, 'Transferencia Bancaria'),
(4, 'Yape/Plin'),
(6, 'Tarjeta de Crédito/Débito');

-- 
-- Dumping data for table clientes
--
INSERT INTO clientes VALUES
(1, 1, '88888888', 'SANTIAGO', 'LOPEZ', '', '', '', '2025-09-02 00:21:20'),
(2, 1, '66666666', 'RODRIGO', 'LOPEZ', '', '', '', '2025-09-02 00:21:32'),
(3, 1, '77777777', 'ADRIAN', 'LOPEZ', '', '', '', '2025-09-02 00:21:43'),
(4, 1, '40000650', 'MGUEL', 'LOPEZ', '', '', '', '2025-09-02 00:21:53');

-- 
-- Dumping data for table tipos_curso
--
INSERT INTO tipos_curso VALUES
(1, 'Piscina', NULL),
(2, 'Gimnasio', NULL),
(3, 'Taller', NULL);

-- 
-- Dumping data for table tipos_horario
--
INSERT INTO tipos_horario VALUES
(1, 'L-M-V', '1,3,5'),
(2, 'M-J-S', '2,4,6'),
(3, 'DIARIO', '1,2,3,4,5,6'),
(4, 'SABADOS', '6');

-- 
-- Dumping data for table sub_areas
--
INSERT INTO sub_areas VALUES
(1, 5, 'CARRIL', '1', 5),
(2, 5, 'CARRIL', '2', 5),
(3, 5, 'CARRIL', '3', 5),
(4, 2, 'CARRIL', '1', 5),
(5, 2, 'CARRIL', '2', 5),
(6, 2, 'CARRIL', '3', 5),
(7, 6, 'CARRIL', '1', 5),
(8, 6, 'CARRIL', '2', 5),
(9, 6, 'CARRIL', '3', 5),
(10, 7, 'TURNO', '1', 50),
(11, 7, 'TURNO', '2', 50);

-- 
-- Dumping data for table matriculas
--
-- Table academia_cursos.matriculas does not contain any data (it is empty)

-- 
-- Dumping data for table tipos_precio
--
INSERT INTO tipos_precio VALUES
(1, 'Precio Regular'),
(2, 'Precio de Lanzamiento');

-- 
-- Dumping data for table cursos
--
INSERT INTO cursos VALUES
(1, 1, 'MAMÁ CON BEBÉ 3 VECES', '', ''),
(2, 1, 'ADULTOS 3 VECES', '', '00004'),
(3, 2, 'GIMNASIO ADULTOS', '', '');

-- 
-- Dumping data for table profesores
--
INSERT INTO profesores VALUES
(1, 1, '44444444', 'SUSANA', 'MORE', 'miguel.lopez@codesicorp.com', '945157875', 'Piscina'),
(2, 1, '66666666', 'ANA', 'MIJARES', 'miguel.lopez@codesicorp.com', '945157875', 'Piscina'),
(3, 1, '00000000', 'MAGALY', 'MEDINA', 'miguel.lopez@codesicorp.com', '945157875', 'Piscina'),
(4, 1, '22222222', 'PEDRO', 'SULCA', 'miguel.lopez@codesicorp.com', '945157875', 'Gimnasio');

-- 
-- Dumping data for table cursos_programados
--
INSERT INTO cursos_programados VALUES
(9, 1, 1, 4, 1, '2025-09-01', '2025-11-30', '10:00:00', '11:00:00', 5, 'Programado'),
(10, 1, 2, 5, 1, '2025-09-01', '2025-09-30', '09:00:00', '11:00:00', 5, 'Programado');

-- 
-- Dumping data for table matriculas_detalle
--
-- Table academia_cursos.matriculas_detalle does not contain any data (it is empty)

-- 
-- Dumping data for table lista_precios
--
INSERT INTO lista_precios VALUES
(1, 2, 1, 350.00, '2025-08-01', '2025-09-30'),
(2, 1, 1, 400.00, '2025-08-01', '2025-09-30'),
(3, 3, 1, 150.00, '2025-08-01', '2025-12-31');

-- 
-- Dumping data for table asistencia_profesor
--
INSERT INTO asistencia_profesor VALUES
(276, 9, 1, '2025-09-01', 'Asistió', ''),
(277, 9, 1, '2025-09-03', 'Asistió', ''),
(278, 9, 1, '2025-09-05', 'Programado', ''),
(279, 9, 1, '2025-09-08', 'Programado', ''),
(280, 9, 1, '2025-09-10', 'Programado', ''),
(281, 9, 1, '2025-09-12', 'Programado', ''),
(282, 9, 1, '2025-09-15', 'Programado', ''),
(283, 9, 1, '2025-09-17', 'Programado', ''),
(284, 9, 1, '2025-09-19', 'Programado', ''),
(285, 9, 1, '2025-09-22', 'Programado', ''),
(286, 9, 1, '2025-09-24', 'Programado', NULL),
(287, 9, 1, '2025-09-26', 'Programado', NULL),
(288, 9, 1, '2025-09-29', 'Programado', NULL),
(289, 9, 1, '2025-10-01', 'Programado', NULL),
(290, 9, 1, '2025-10-03', 'Programado', NULL),
(291, 9, 1, '2025-10-06', 'Programado', NULL),
(292, 9, 1, '2025-10-08', 'Programado', NULL),
(293, 9, 1, '2025-10-10', 'Programado', NULL),
(294, 9, 1, '2025-10-13', 'Programado', NULL),
(295, 9, 1, '2025-10-15', 'Programado', NULL),
(296, 9, 1, '2025-10-17', 'Programado', NULL),
(297, 9, 1, '2025-10-20', 'Programado', NULL),
(298, 9, 1, '2025-10-22', 'Programado', NULL),
(299, 9, 1, '2025-10-24', 'Programado', NULL),
(300, 9, 1, '2025-10-27', 'Programado', NULL),
(301, 9, 1, '2025-10-29', 'Programado', NULL),
(302, 9, 1, '2025-10-31', 'Programado', NULL),
(303, 9, 1, '2025-11-03', 'Programado', NULL),
(304, 9, 1, '2025-11-05', 'Programado', NULL),
(305, 9, 1, '2025-11-07', 'Programado', NULL),
(306, 9, 1, '2025-11-10', 'Programado', NULL),
(307, 9, 1, '2025-11-12', 'Programado', NULL),
(308, 9, 1, '2025-11-14', 'Programado', NULL),
(309, 9, 1, '2025-11-17', 'Programado', NULL),
(310, 9, 1, '2025-11-19', 'Programado', NULL),
(311, 9, 1, '2025-11-21', 'Programado', NULL),
(312, 9, 1, '2025-11-24', 'Programado', NULL),
(313, 9, 1, '2025-11-26', 'Programado', NULL),
(314, 9, 1, '2025-11-28', 'Programado', NULL),
(315, 10, 2, '2025-09-01', 'Programado', NULL),
(316, 10, 2, '2025-09-03', 'Programado', NULL),
(317, 10, 2, '2025-09-05', 'Programado', NULL),
(318, 10, 2, '2025-09-08', 'Programado', NULL),
(319, 10, 2, '2025-09-10', 'Programado', NULL),
(320, 10, 2, '2025-09-12', 'Programado', NULL),
(321, 10, 2, '2025-09-15', 'Programado', NULL),
(322, 10, 2, '2025-09-17', 'Programado', NULL),
(323, 10, 2, '2025-09-19', 'Programado', NULL),
(324, 10, 2, '2025-09-22', 'Programado', NULL),
(325, 10, 2, '2025-09-24', 'Programado', NULL),
(326, 10, 2, '2025-09-26', 'Programado', NULL),
(327, 10, 2, '2025-09-29', 'Programado', NULL);

-- 
-- Dumping data for table asistencia_cliente
--
-- Table academia_cursos.asistencia_cliente does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;